# Generated by Django 3.1.3 on 2020-11-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(max_length=1500)),
                ('link', models.CharField(max_length=600)),
                ('author', models.CharField(max_length=300)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('number_of_measured_properties', models.PositiveIntegerField(default=1)),
                ('number_of_samples', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
