# Generated by Django 3.1.3 on 2020-11-28 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_auto_20201128_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experiment',
            name='detailed_metrics',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='product',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='public_view',
        ),
        migrations.RemoveField(
            model_name='experiment',
            name='samples',
        ),
    ]
