# Generated by Django 3.1.3 on 2020-12-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_experiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='value',
            field=models.CharField(max_length=1500),
        ),
    ]
